[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mtc"
version = "0.1.0"
description = "AI-powered Manual Test Case generation service"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["dependencies"]

[project.optional-dependencies]
dev = []

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
include = ["src*"]

[tool.setuptools.package-data]
"*" = ["*.txt"]
